spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    username: sa
    password:
    url: jdbc:h2:~/paydemo

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true